{"name": "Ошибка при проверке пользователя с некорректным паролем", "status": "passed", "start": 1714680875843, "stop": 1714680876286, "uuid": "f997ac56-8892-44ed-8b1d-4cf763a68930", "historyId": "1733dacbd25b6cef31bcbafd9c89f245", "testCaseId": "1733dacbd25b6cef31bcbafd9c89f245", "fullName": "tests.test_user_login.TestUserLogin#test_login_incorrect_password_failed_result", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-6OEUNT0"}, {"name": "thread", "value": "4572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}
